CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    uid VARCHAR(36) UNIQUE NOT NULL,
    number VARCHAR(15) UNIQUE,
    email VARCHAR(255) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);